---
- hosts: all
  become: true
  tasks:
    - name: copy script hosts
      copy:
        src: script/hosts.sh 
        dest: /etc/profile.d/hosts.sh
        owner: root 
        group: root
        mode: 0751
    - name: the hosts converted to variables
      shell: |
        source /etc/profile.d/hosts.sh
      args:
        chdir: /etc/profile.d/
        executable: /bin/bash

        
    - name: Directory
      file:
        path: "{{ item }}"
        state: directory
        recurse: true
        owner: root
        group: root
        mode: 0751
      with_items:
        - /var/lib/etcd
        - /var/lib/k8s
        - /etc/etcd
        - /usr/local/bin/etcd/bin

    - name: "Create user group"
      shell: |
        sudo groupadd --system etcd
        sudo useradd -s /sbin/nologin --system -g etcd etcd
        sudo chown -R etcd:etcd /var/lib/etcd
        
#    - name: Make direcories
#      file:
#        path: "{{ item }}"
#        state: touch
#        owner: etcd 
#        group: etcd
#        mode: 0751
#      with_items:
#        - /etc/systemd/system/etcd.service

      
    - name: encryption
      shell: head -c 32 /dev/urandom | base64 
      register: result
    - name: The encryption key
      blockinfile:
        marker: "#<!-- github.com/dczinil {mark} ansible block -->#"
        owner: etcd 
        group: etcd
        mode: 0751
        path: /var/lib/k8s/encryption-config.yaml
        create: true
        block: |
          kind: EncryptionConfig
          apiVersion: v1
          resources:
            - resources:
              - secrets
              providers:
              - aescbc:
                keys:
                - name: key1
                  secret: {{ result.stdout  }}
              - identity: {}

    - name: install Golang upstream
      unarchive:
        src: https://dl.google.com/go/go1.20.1.linux-amd64.tar.gz
        dest: /usr/local/
        remote_src: True
    - name: Set custom Golang path root
      blockinfile: 
        marker: "#<!-- github.com/dczinil {mark} ansible block -->#"
        path: /root/.bashrc
        block: |
          export GOPATH=/home/vagrant/go
          export GOBIN=$GOPATH/bin
          export GOROOT=/usr/local/go
          export PATH=$PATH:$GOBIN:$GOROOT/bin
    - name: Set Custom Golang path User
      blockinfile: 
        marker: "#<!-- github.com/dczinil {mark} ansible block -->#"
        path: /home/vagrant/.bashrc
        block: |
          export GOPATH=/home/vagrant/go
          export GOBIN=$GOPATH/bin
          export GOROOT=/usr/local/go
          export PATH=$PATH:$GOBIN:$GOROOT/bin
    - name: link golang
      file: src=/usr/local/go/bin/go dest=/bin/go state=link
    - name: Install a list of packages
      apt:
        state: present
        update_cache: yes
        cache_valid_time: 86400
        pkg:
        - ca-certificates
        - curl
        - wget
        - gnupg-agent
        - software-properties-common
        - apt-transport-https
        - net-tools
        - pipexec
        - tree

    - name: copy encryption ca
      copy:
        content: script/cert/ca.pem
        dest: /etc/etcd/ca.pem
        force: yes
        remote_src: yes
    - name: copy encryption k8s
      copy:
        content: script/cert/kubernetes.pem
        dest: /etc/etcd/kubernetes.pem
        force: yes
        remote_src: yes
    - name: copy encryption pem
      copy:
        content: script/cert/kubernetes-key.pem
        dest: /etc/etcd/kubernetes-key.pem
        force: yes
        remote_src: yes

    - name: "Download etcd.tar.gz"
      get_url:
        url: https://github.com/etcd-io/etcd/releases/download/v3.5.7/etcd-v3.5.7-linux-amd64.tar.gz
        dest: /tmp/etcd-v3.5.7-linux-amd64.tar.gz
        owner: etcd
        group: etcd
        mode: 0751
        force: True
    - name: "Extract etcd.tar.gz"
      shell: |
        tar -zxvf /tmp/etcd-v3.5.7-linux-amd64.tar.gz -C /usr/local/bin/etcd/bin/ --strip-components=1
        rm -rf /tmp/etcd-v3.5.7-linux-amd64*
    - name: "set permission etcd"
      file:
        path: /usr/local/bin/etcd/bin/etcd 
        state: file
        owner: root
        group: root
        mode: 0751
    - name: "set permission etcdctl"
      file:
        path: /usr/local/bin/etcd/bin/etcdctl 
        state: file
        owner: root
        group: root
        mode: 0751
    - name: "Set ETCDCTL_API enviroment 3"
      blockinfile:
        marker: "#<!-- github.com/dczinil {mark} ansible block -->#"
        path: /etc/profile
        block: |
          export ETCDCTL_API=3
          export PATH="$PATH:/usr/local/bin/etcd/bin"
        state: present
        insertafter: EOF

    - name: "Create config file for etcd"
      template:
        src: fileconf/etcd.conf.yaml.j2
        dest: /etc/etcd/etcd.conf.yaml
    - name: "Service etcd"
      template:
        src: fileconf/etcd.service.yaml.j2
        dest: /etc/systemd/system/etcd.service
#    - name: "Create a etcd service"
#      blockinfile:
#        src: 
#        block: |
#          [Unit]
#          Description=etcd key-value store
#          Documentation=https://github.com/coreos/etcd
#          After=network.target
#          Wants=network-online.target
#          
#          [Service]
#          Environment=DAEMON_ARGS=/etc/etcd/etcd.conf.yaml
#          Type=notify
#          User=etcd
#          PermissionsStartOnly=true
#          ExecStart=/usr/local/bin/etcd/bin/etcd $DAEMON_ARGS
#          Restart=on-abnormal
#          LimitNOFILE=65536
#          
#          [Install]
#          WantedBy=multi-user.target
#          Alias=etcd2.service

    - name: "Start enable etcd"
      shell: |
        sudo systemctl start etcd
        sudo systemctl enable etcd
    - name: Testing
      shell: |
        etcdctl put foo bar
        etcdctl get foo
...
#          [Unit]
#          Description=etcd distributed reliable key-value store
#          After=network-online.target local-fs.target remote-fs.target
#          Wants=network-online.target local-fs.target remote-fs.target
#
#          [Service]
#          Type=notify
#          ExecStart=/usr/local/bin/etcd/bin/etcd --config-file /etc/etcd/etcd.conf
#          Restart=always
