---
- hosts: all
  become: true
  tasks:
#     - name: Install a list of packages
#       apt:
#         state: present
#         update_cache: yes
#         cache_valid_time: 86400
#         pkg:
#         - ca-certificates
#         - curl
#         - gnupg-agent
#         - software-properties-common
# 
#     - name: Create file crio
#       file:
#         path: /etc/modules-load.d/crio.conf
#         state: touch
# 
#     - name:
#       blockinfile:
#         path: /etc/modules-load.d/crio.conf
#         block: |
#           overlay
#           br_netfilter
# 
#     - name: Enable sysctl params
#       file:
#         path: /etc/sysctl.d/99-kubernetes-cri.conf
#         state: touch
# 
#     - name: add configuration
#       blockinfile: 
#         path: /etc/sysctl.d/99-kubernetes-cri.conf
#         block: |
#           net.bridge.bridge-nf-call-iptables = 1
#           net.ipv4.ip_forward = 1
#           net.bridge.bridge-nf-call-ip6tables = 1
# 
#     - name: enable overlayFS & VxLan
#       shell: |
#         sudo modprobe overlay
#         sudo modprobe br_netfilter
#     - name: Reload parameters
#       command: sudo sysctl --system
# 
#     - name: Remove swapfile from /etc/fstab
#       mount:
#         name: "{{ item }}"
#         fstype: swap
#         state: absent
#       with_items:
#         - swap
#         - none
#     - name: Disable swap
#       command: swapoff -a
#       when: ansible_swaptotal_mb > 0
# 
#     - name: install Golang upstream
#       unarchive:
#         src: https://dl.google.com/go/go1.20.1.linux-amd64.tar.gz
#         dest: /usr/local/
#         remote_src: True
#     - name: creates directory
#       file:
#         path: /home/vagrant/go
#         state: directory
#     - name: Set custom Golang path 
#       blockinfile: 
#         path: /root/.bashrc
#         block: |
#           export GOPATH=/home/vagrant/go
#           export GOBIN=$GOPATH/bin
#           export GOROOT=/usr/local/go
#           export PATH=$PATH:$GOBIN:$GOROOT/bin
#     - name: link golang
#       file: src=/usr/local/go/bin/go dest=/bin/go state=link
# 
#     - name: enable cri-repo
#       environment:
#           OS: xUbuntu_20.04
#           VERSION: 1.24
#       shell: |
#         echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
#         echo "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.list
#         curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/Release.key | apt-key add -
#         curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | apt-key add -
#     - name: Install cri-o cri-o-runc cri-tools
#       apt:
#         state: present
#         update_cache: yes
#         pkg:
#         - cri-o
#         - cri-o-runc
#         - cri-tools

    - name: copy script
      copy: 
        src: script/hosts.sh 
        dest: /home/vagrant 
        mode: 0710
    - name: the hosts converted to variables
      shell: /home/vagrant/hosts.sh >> /home/vagrant/.bashrc
      args:
        chdir: /home/vagrant
        executable: /bin/bash
